pub mod agent;
pub mod chats;
pub mod config;
pub mod console;
pub mod cron;
pub mod download;
pub mod envs;
pub mod local_models;
pub mod mcp;
pub mod models;
pub mod ollama_models;
pub mod schemas;
pub mod skills;
pub mod workspace;

pub use agent::{create_agent_router, AgentState};
pub use chats::{create_chats_router, ChatsState};
pub use config::{create_config_router, ConfigState, HasConfigState};
pub use console::create_console_router;
pub use cron::{create_cron_router, CronState, HasCronState};
pub use download::DownloadManager;
pub use envs::{create_envs_router, EnvsState, HasEnvsState};
pub use local_models::{create_local_models_router, LocalModelsState, LOCAL_MODELS_DIR};
pub use mcp::{create_mcp_router, HasMcpState, McpState};
pub use models::{create_models_router, ModelsState};
pub use ollama_models::{create_ollama_models_router, OllamaModelsState};
pub use skills::create_skills_router;
pub use workspace::create_workspace_router;
